name: superchickentimerflutter
description: "Super Chicken Timer"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  
  
  
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  app_tracking_transparency: ^2.0.6+1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  appsflyer_sdk: ^6.17.5
  shared_preferences: ^2.5.3
  webview_flutter_wkwebview: ^3.23.1
  url_launcher: ^6.3.2
  external_app_launcher: ^4.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations

flutter:
  uses-material-design: true
  assets:
    # - assets/animations/
    - assets/images/
  generate: true

